### ISSUE TITLE
Fix editable install

### ISSUE THREAD

**Issue by tierriminator** [MeteoSwiss-APN/finch#18]
Currently, we cannot run `pip install -e .` for installation during development.
Unfortunately, it does not properly install the `zebra.zebra` extension module.

### Tasks:

- [ ] Figure out why editable install does not work (why zebra.zebra isn't built and installed)
- [ ] Fix whatever needs to be fixed
- [ ] Adjust the documentation
- [ ] Adjust the `dev_env` github action
